<?php

namespace Database\Seeders;

use App\Models\ProductBrand;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $records = [
            ['title' => ucfirst('Migali'), 'slug' => 'migali', 'image' => 'migali.png', 'is_featured' => 1, 'order' => 1, 'created_at' => now()],
            ['title' => ucfirst('concassé'), 'slug' => 'concasse', 'image' => 'concasse.png', 'is_featured' => 1, 'order' => 2, 'created_at' => now()],
            ['title' => ucfirst('avantco'), 'slug' => 'avantco', 'image' => 'avantco.png', 'is_featured' => 1, 'order' => 3, 'created_at' => now()],
            ['title' => ucfirst('choice'), 'slug' => 'choice', 'image' => 'choice.png', 'is_featured' => 1, 'order' => 4, 'created_at' => now()],
            ['title' => ucfirst('galaxy'), 'slug' => 'galaxy', 'image' => 'galaxy.png', 'is_featured' => 1, 'order' => 5, 'created_at' => now()],
            ['title' => ucfirst('hobart'), 'slug' => 'hobart', 'image' => 'hobart.png', 'is_featured' => 1, 'order' => 6, 'created_at' => now()],
            ['title' => ucfirst('unox'), 'slug' => 'unox', 'image' => 'unox.png', 'is_featured' => 1, 'order' => 7, 'created_at' => now()],
            ['title' => ucfirst('migsa'), 'slug' => 'migsa', 'image' => 'migsa.png', 'is_featured' => 1, 'order' => 8, 'created_at' => now()],
            ['title' => ucfirst('sammic'), 'slug' => 'sammic', 'image' => 'sammic.png', 'is_featured' => 1, 'order' => 9, 'created_at' => now()],
            ['title' => ucfirst('waring'), 'slug' => 'waring', 'image' => 'waring.png', 'is_featured' => 1, 'order' => 10, 'created_at' => now()],
            ['title' => ucfirst('atosa'), 'slug' => 'atosa', 'image' => 'atosa.png', 'is_featured' => 1, 'order' => 11, 'created_at' => now()],
            ['title' => ucfirst('coriat'), 'slug' => 'coriat', 'image' => 'coriat.png', 'is_featured' => 1, 'order' => 12, 'created_at' => now()],
            ['title' => ucfirst('international'), 'slug' => 'international', 'image' => 'international.png', 'is_featured' => 1, 'order' => 13, 'created_at' => now()],
            ['title' => ucfirst('friocima'), 'slug' => 'friocima', 'image' => 'friocima.png', 'is_featured' => 1, 'order' => 14, 'created_at' => now()],
            ['title' => ucfirst('crathco'), 'slug' => 'crathco', 'image' => 'crathco.png', 'is_featured' => 1, 'order' => 15, 'created_at' => now()],
            ['title' => ucfirst('imperial Range'), 'slug' => 'imperial-range', 'image' => 'imperial-range.png', 'is_featured' => 1, 'order' => 16, 'created_at' => now()],
            ['title' => ucfirst('rational'), 'slug' => 'rational', 'image' => 'rational.png', 'is_featured' => 1, 'order' => 17, 'created_at' => now()],
            ['title' => ucfirst('ecomax'), 'slug' => 'ecomax', 'image' => 'ecomax.png', 'is_featured' => 1, 'order' => 18, 'created_at' => now()],
            ['title' => ucfirst('winterhalter'), 'slug' => 'winterhalter', 'image' => 'winterhalter.png', 'is_featured' => 1, 'order' => 19, 'created_at' => now()],
            ['title' => ucfirst('edenox'), 'slug' => 'edenox', 'image' => 'edenox.png', 'is_featured' => 1, 'order' => 20, 'created_at' => now()],
            ['title' => ucfirst('fisher'), 'slug' => 'fisher', 'image' => 'fisher.png', 'is_featured' => 1, 'order' => 21, 'created_at' => now()],
            ['title' => ucfirst('globe'), 'slug' => 'globe', 'image' => 'globe.png', 'is_featured' => 1, 'order' => 22, 'created_at' => now()],
            ['title' => ucfirst('hatco'), 'slug' => 'hatco', 'image' => 'hatco.png', 'is_featured' => 1, 'order' => 23, 'created_at' => now()],
            ['title' => ucfirst('ice-o-matic'), 'slug' => 'ice-o-matic', 'image' => 'ice-o-matic.png', 'is_featured' => 1, 'order' => 24, 'created_at' => now()],
            ['title' => ucfirst('intertécnica'), 'slug' => 'intertecnica', 'image' => 'intertecnica.png', 'is_featured' => 1, 'order' => 25, 'created_at' => now()],
            ['title' => ucfirst('metro'), 'slug' => 'metro', 'image' => 'metro.png', 'is_featured' => 1, 'order' => 26, 'created_at' => now()],
            ['title' => ucfirst('vitamix'), 'slug' => 'vitamix', 'image' => 'vitamix.png', 'is_featured' => 1, 'order' => 27, 'created_at' => now()],
            ['title' => ucfirst('vulcan'), 'slug' => 'vulcan', 'image' => 'vulcan.png', 'is_featured' => 1, 'order' => 28, 'created_at' => now()],
            ['title' => ucfirst('casadio'), 'slug' => 'casadio', 'image' => 'casadio.png', 'is_featured' => 1, 'order' => 29, 'created_at' => now()],
            ['title' => ucfirst('teknikitchen'), 'slug' => 'teknikitchen', 'image' => 'teknikitchen.png', 'is_featured' => 1, 'order' => 30, 'created_at' => now()],
            ['title' => ucfirst('nemco'), 'slug' => 'nemco', 'image' => 'nemco.png', 'is_featured' => 1, 'order' => 31, 'created_at' => now()],
            ['title' => ucfirst('adcraft'), 'slug' => Str::slug('adcraft'), 'image' => 'null.webp', 'order' => 32, 'created_at' => now()],
            ['title' => ucfirst('advance'), 'slug' => Str::slug('advance'), 'image' => 'null.webp', 'order' => 33, 'created_at' => now()],
            ['title' => ucfirst('alpro'), 'slug' => Str::slug('alpro'), 'image' => 'null.webp', 'order' => 34, 'created_at' => now()],
            ['title' => ucfirst('amana'), 'slug' => Str::slug('amana'), 'image' => 'null.webp', 'order' => 35, 'created_at' => now()],
            ['title' => ucfirst('asber'), 'slug' => Str::slug('asber'), 'image' => 'null.webp', 'order' => 36, 'created_at' => now()],
            ['title' => ucfirst('ascaso'), 'slug' => Str::slug('ascaso'), 'image' => 'null.webp', 'order' => 37, 'created_at' => now()],
            ['title' => ucfirst('AvaValley'), 'slug' => Str::slug('AvaValley'), 'image' => 'null.webp', 'order' => 38, 'created_at' => now()],
            ['title' => ucfirst('balance'), 'slug' => Str::slug('balance'), 'image' => 'null.webp', 'order' => 39, 'created_at' => now()],
            ['title' => ucfirst('barmaid'), 'slug' => Str::slug('barmaid'), 'image' => 'null.webp', 'order' => 40, 'created_at' => now()],
            ['title' => ucfirst('bellini'), 'slug' => Str::slug('bellini'), 'image' => 'null.webp', 'order' => 41, 'created_at' => now()],
            ['title' => ucfirst('blendtec'), 'slug' => Str::slug('blendtec'), 'image' => 'null.webp', 'order' => 42, 'created_at' => now()],
            ['title' => ucfirst('bunn'), 'slug' => Str::slug('bunn'), 'image' => 'null.webp', 'order' => 43, 'created_at' => now()],
            ['title' => ucfirst('cambro'), 'slug' => Str::slug('cambro'), 'image' => 'null.webp', 'order' => 44, 'created_at' => now()],
            ['title' => ucfirst('centerline'), 'slug' => Str::slug('centerline'), 'image' => 'null.webp', 'order' => 45, 'created_at' => now()],
            ['title' => ucfirst('cimbali'), 'slug' => Str::slug('cimbali'), 'image' => 'null.webp', 'order' => 46, 'created_at' => now()],
            ['title' => ucfirst('crathco simplicity'), 'slug' => Str::slug('crathco simplicity'), 'image' => 'null.webp', 'order' => 47, 'created_at' => now()],
            ['title' => ucfirst('criotec'), 'slug' => Str::slug('criotec'), 'image' => 'null.webp', 'order' => 48, 'created_at' => now()],
            ['title' => ucfirst('delfield'), 'slug' => Str::slug('delfield'), 'image' => 'null.webp', 'order' => 49, 'created_at' => now()],
            ['title' => ucfirst('disa'), 'slug' => Str::slug('disa'), 'image' => 'null.webp', 'order' => 50, 'created_at' => now()],
            ['title' => ucfirst('drago'), 'slug' => Str::slug('drago'), 'image' => 'null.webp', 'order' => 51, 'created_at' => now()],
            ['title' => ucfirst('duke'), 'slug' => Str::slug('duke'), 'image' => 'null.webp', 'order' => 52, 'created_at' => now()],
            ['title' => ucfirst('dynamic'), 'slug' => Str::slug('dynamic'), 'image' => 'null.webp', 'order' => 53, 'created_at' => now()],
            ['title' => ucfirst('edlund'), 'slug' => Str::slug('edlund'), 'image' => 'null.webp', 'order' => 54, 'created_at' => now()],
            ['title' => ucfirst('equi-par'), 'slug' => Str::slug('equi-par'), 'image' => 'null.webp', 'order' => 55, 'created_at' => now()],
            ['title' => ucfirst('equichef'), 'slug' => Str::slug('equichef'), 'image' => 'null.webp', 'order' => 56, 'created_at' => now()],
            ['title' => ucfirst('estella'), 'slug' => Str::slug('estella'), 'image' => 'null.webp', 'order' => 57, 'created_at' => now()],
            ['title' => ucfirst('flexcool'), 'slug' => Str::slug('flexcool'), 'image' => 'null.webp', 'order' => 58, 'created_at' => now()],
            ['title' => ucfirst('grindmaster'), 'slug' => Str::slug('grindmaster'), 'image' => 'null.webp', 'order' => 59, 'created_at' => now()],
            ['title' => ucfirst('hoffman'), 'slug' => Str::slug('hoffman'), 'image' => 'null.webp', 'order' => 60, 'created_at' => now()],
            ['title' => ucfirst('icehaus'), 'slug' => Str::slug('icehaus'), 'image' => 'null.webp', 'order' => 61, 'created_at' => now()],
            ['title' => ucfirst('imbera'), 'slug' => Str::slug('imbera'), 'image' => 'null.webp', 'order' => 62, 'created_at' => now()],
            ['title' => ucfirst('imperial'), 'slug' => Str::slug('imperial'), 'image' => 'null.webp', 'order' => 63, 'created_at' => now()],
            ['title' => ucfirst('insinkerator'), 'slug' => Str::slug('insinkerator'), 'image' => 'null.webp', 'order' => 64, 'created_at' => now()],
            ['title' => ucfirst('jackson'), 'slug' => Str::slug('jackson'), 'image' => 'null.webp', 'order' => 65, 'created_at' => now()],
            ['title' => ucfirst('jiwins'), 'slug' => Str::slug('jiwins'), 'image' => 'null.webp', 'order' => 66, 'created_at' => now()],
            ['title' => ucfirst('keystone'), 'slug' => Str::slug('keystone'), 'image' => 'null.webp', 'order' => 67, 'created_at' => now()],
            ['title' => ucfirst('kitchenaid'), 'slug' => Str::slug('kitchenaid'), 'image' => 'null.webp', 'order' => 68, 'created_at' => now()],
            ['title' => ucfirst('lakeside'), 'slug' => Str::slug('lakeside'), 'image' => 'null.webp', 'order' => 69, 'created_at' => now()],
            ['title' => ucfirst('magister'), 'slug' => Str::slug('magister'), 'image' => 'null.webp', 'order' => 70, 'created_at' => now()],
            ['title' => ucfirst('mahlkönig'), 'slug' => Str::slug('mahlkonig'), 'image' => 'null.webp', 'order' => 71, 'created_at' => now()],
            ['title' => ucfirst('matfer Bourgeat'), 'slug' => Str::slug('matfer Bourgeat'), 'image' => 'null.webp', 'order' => 72, 'created_at' => now()],
            ['title' => ucfirst('mazzer'), 'slug' => Str::slug('mazzer'), 'image' => 'null.webp', 'order' => 73, 'created_at' => now()],
            ['title' => ucfirst('metalfrio'), 'slug' => Str::slug('metalfrio'), 'image' => 'null.webp', 'order' => 74, 'created_at' => now()],
            ['title' => ucfirst('metrology'), 'slug' => Str::slug('metrology'), 'image' => 'null.webp', 'order' => 75, 'created_at' => now()],
            ['title' => ucfirst('mibrasa'), 'slug' => Str::slug('mibrasa'), 'image' => 'null.webp', 'order' => 76, 'created_at' => now()],
            ['title' => ucfirst('midea'), 'slug' => Str::slug('midea'), 'image' => 'null.webp', 'order' => 77, 'created_at' => now()],
            ['title' => ucfirst('noval'), 'slug' => Str::slug('noval'), 'image' => 'null.webp', 'order' => 78, 'created_at' => now()],
            ['title' => ucfirst('olympic'), 'slug' => Str::slug('olympic'), 'image' => 'null.webp', 'order' => 79, 'created_at' => now()],
            ['title' => ucfirst('optipure'), 'slug' => Str::slug('optipure'), 'image' => 'null.webp', 'order' => 80, 'created_at' => now()],
            ['title' => ucfirst('oster'), 'slug' => Str::slug('oster'), 'image' => 'null.webp', 'order' => 81, 'created_at' => now()],
            ['title' => ucfirst('polyscience'), 'slug' => Str::slug('polyscience'), 'image' => 'null.webp', 'order' => 82, 'created_at' => now()],
            ['title' => ucfirst('preppal'), 'slug' => Str::slug('preppal'), 'image' => 'null.webp', 'order' => 83, 'created_at' => now()],
            ['title' => ucfirst('rhino'), 'slug' => Str::slug('rhino'), 'image' => 'null.webp', 'order' => 84, 'created_at' => now()],
            ['title' => ucfirst('robot coupe'), 'slug' => Str::slug('robot coupe'), 'image' => 'null.webp', 'order' => 85, 'created_at' => now()],
            ['title' => ucfirst('rubbermaid'), 'slug' => Str::slug('rubbermaid'), 'image' => 'null.webp', 'order' => 86, 'created_at' => now()],
            ['title' => ucfirst('samas'), 'slug' => Str::slug('samas'), 'image' => 'null.webp', 'order' => 87, 'created_at' => now()],
            ['title' => ucfirst('skymsen'), 'slug' => Str::slug('skymsen'), 'image' => 'null.webp', 'order' => 88, 'created_at' => now()],
            ['title' => ucfirst('solwave'), 'slug' => Str::slug('solwave'), 'image' => 'null.webp', 'order' => 89, 'created_at' => now()],
            ['title' => ucfirst('stay safe'), 'slug' => Str::slug('stay safe'), 'image' => 'null.webp', 'order' => 90, 'created_at' => now()],
            ['title' => 'T&S', 'slug' => Str::slug('T&S'), 'image' => 'null.webp', 'order' => 91, 'created_at' => now()],
            ['title' => ucfirst('tahona'), 'slug' => Str::slug('tahona'), 'image' => 'null.webp', 'order' => 92, 'created_at' => now()],
            ['title' => ucfirst('tramontina'), 'slug' => Str::slug('tramontina'), 'image' => 'null.webp', 'order' => 93, 'created_at' => now()],
            ['title' => ucfirst('ugolini'), 'slug' => Str::slug('ugolini'), 'image' => 'null.webp', 'order' => 94, 'created_at' => now()],
            ['title' => ucfirst('uptate'), 'slug' => Str::slug('uptate'), 'image' => 'null.webp', 'order' => 95, 'created_at' => now()],
            ['title' => ucfirst('vinson'), 'slug' => Str::slug('vinson'), 'image' => 'null.webp', 'order' => 96, 'created_at' => now()],
            ['title' => ucfirst('vito Fryfilter'), 'slug' => Str::slug('vito Fryfilter'), 'image' => 'null.webp', 'order' => 97, 'created_at' => now()],
            ['title' => ucfirst('waring Commercial'), 'slug' => Str::slug('waring Commercial'), 'image' => 'null.webp', 'order' => 98, 'created_at' => now()],
            ['title' => ucfirst('winco'), 'slug' => Str::slug('winco'), 'image' => 'null.webp', 'order' => 99, 'created_at' => now()],
            ['title' => ucfirst('zumex'), 'slug' => Str::slug('zumex'), 'image' => 'null.webp', 'order' => 100, 'created_at' => now()],

        ];
        ProductBrand::insert($records);
    }
}
